//go:build js && wasm
// +build js,wasm

// Code generated by "stringer -type EngineCallbackID wasm/gameengine.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EngineOnPublishJson-0]
	_ = x[EngineOnPublishJsonTemporary-1]
	_ = x[EngineOnRemove-2]
	_ = x[EngineOnRemoveAll-3]
	_ = x[EngineOnCommandRequested-4]
	_ = x[EngineOnInputRequested-5]
	_ = x[EngineOnInputRequestClosed-6]
	_ = x[EngineNotifyQuit-7]
}

const _EngineCallbackID_name = "EngineOnPublishJsonEngineOnPublishJsonTemporaryEngineOnRemoveEngineOnRemoveAllEngineOnCommandRequestedEngineOnInputRequestedEngineOnInputRequestClosedEngineNotifyQuit"

var _EngineCallbackID_index = [...]uint8{0, 19, 47, 61, 78, 102, 124, 150, 166}

func (i EngineCallbackID) String() string {
	if i < 0 || i >= EngineCallbackID(len(_EngineCallbackID_index)-1) {
		return "EngineCallbackID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EngineCallbackID_name[_EngineCallbackID_index[i]:_EngineCallbackID_index[i+1]]
}
